### ISSUE TITLE
Version solving failure when using jaguar_orm together with built_value

### ISSUE THREAD

**Issue by AlexanderArendar** [Jaguar-dart/jaguar_orm#162]
Hi there,

I use built_value in my project, like the most of production projects do.
Today I decided to add a dependency to "jaguar_orm" and try to use it but when I run the `pub get` I see the following output:
```
Resolving dependencies... (2.8s)
The current Dart SDK version is 2.5.0.

    Because no versions of analyzer_plugin match >0.1.0 <0.3.0 and analyzer_plugin 0.1.0 depends on analyzer >=0.35.3 <0.38.0, analyzer_plugin >=0.1.0 <0.3.0 requires analyzer >=0.35.3 <0.38.0.
(1) So, because jaguar_orm_gen >=2.2.27 depends on analyzer ^0.34.0, analyzer_plugin >=0.1.0 <0.3.0 is incompatible with jaguar_orm_gen >=2.2.27.

    Because jaguar_orm_gen <2.2.2 requires SDK version >=2.0.0-dev.55.0 <2.0.0 and jaguar_orm_gen >=2.2.2 <2.2.18 depends on build ^0.12.0, jaguar_orm_gen <2.2.18 requires build ^0.12.0.
    And because jaguar_orm_gen >=2.2.18 <2.2.27 depends on analyzer ^0.33.0, jaguar_orm_gen <2.2.27 requires build ^0.12.0 or analyzer ^0.33.0.
    And because analyzer_plugin >=0.1.0 <0.3.0 is incompatible with jaguar_orm_gen >=2.2.27 (1), if analyzer_plugin >=0.1.0 <0.3.0 and jaguar_orm_gen any then build ^0.12.0 or analyzer ^0.33.0.
    And because built_value_generator 6.7.1 depends on both build ^1.0.0 and analyzer >=0.34.0 <0.37.0, one of analyzer_plugin >=0.1.0 <0.3.0 or jaguar_orm_gen any or built_value_generator 6.7.1 must be false.
    And because built_value_generator 6.7.1 depends on analyzer_plugin >=0.1.0 <0.3.0 and no versions of built_value_generator match >6.7.1 <7.0.0, jaguar_orm_gen is incompatible with built_value_generator ^6.7.1.
    So, because qa depends on both jaguar_orm_gen any and built_value_generator ^6.7.1, version solving failed.

```

Could you advise?
My `pubspec.yaml` below:
```
environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  safe_config: ^2.0.2
  matcher: ^0.12.5
  built_value: ^6.7.1
  built_collection: ^4.2.2
  intl: ^0.16.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
  webdriver: any
  build_runner: ^1.6.9
  built_value_generator: ^6.7.1
  jaguar_orm: ^2.2.6
  jaguar_orm_gen: 
```
