### ISSUE TITLE
missing implementations for these member Adapter.alter

### ISSUE THREAD

**Issue by u007** [Jaguar-dart/jaguar_orm#171]
got this error:

my pubspec:
```
dependencies:
  # ...
  dotenv: ^2.0.0
  mysql1: ^0.17.0+1
  jaguar_query_sqljocky: ^2.2.4
  jaguar_orm: ^2.2.7
  
dev_dependencies:
  build_runner: ^1.5.0
  jaguar_orm_gen: ^2.2.29

```

```
jaguar_query_sqljocky-2.2.4/lib/src/adapter.dart:12:7: Error: The non-abstract class 'MysqlAdapter' is missing implementations for these members:
 - Adapter.alter
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class MysqlAdapter implements Adapter<sj.MySqlConnection> {

```
