### ISSUE TITLE
analyzer version too low for compatibility with null-safe packages

### ISSUE THREAD

**Issue by SebastienSCochet** [Jaguar-dart/jaguar_orm#197]
Everything is in the title

**Comment by JamesMcIntosh** [comment]
@SebastienSCochet I did a null-safe migration of the LegacyV3 branch, not sure if that helps

https://github.com/JamesMcIntosh/jaguar_orm/tree/legacyV3

It's not too far of what's actually in master, doesn't seem like much has changed since the V3 branch

https://github.com/Jaguar-dart/jaguar_orm/compare/legacyV3

**Comment by isaacfi** [comment]
Hi,

I tried to use your verson @SebastienSCochet, but I got a lot of problems with the generator, and I did my own implementation of null safety based on the next versions:

**Flutter: 1.22.6**

```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  jaguar_orm: ^2.2.7
  jaguar_query_sqflite: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.2.2
  jaguar_orm_gen: ^2.2.30
  analyzer: ^0.38.0
  build_resolvers: ^1.2.0
  json_serializable: ^3.0.0
```

If you know how to publish in the flutter package repository [pub.dev](https://pub.dev/packages) or if you have some documentation to follow, please share it.

If you want to use my implementation in your flutter projects, just change the references as this:

**Flutter: 2.2.3**

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  jaguar_orm:
    git:
      url: https://github.com/isaacfi/jaguar_orm_nullsafe.git
      path: orm
  jaguar_query_sqflite:
    git:
      url: https://github.com/isaacfi/jaguar_orm_nullsafe.git
      path: sqflite

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  jaguar_orm_gen:
    git:
      url: https://github.com/isaacfi/jaguar_orm_nullsafe.git
      path: generator
  analyzer: ^1.5.0
  build_resolvers: ^2.0.4
  json_serializable: ^4.1.4

dependency_overrides:
  meta: ^1.3.0
```
