### ISSUE TITLE
Flutter usage

### ISSUE THREAD

**Issue by jaumard** [Jaguar-dart/jaguar_orm#20]
Is it possible to use this package with Flutter (sqlite database) ? 
Would be awesome as currently on Flutter there nothing as I know (except plugin to make raw sql queries...).

If it doesn't work with Flutter can it work ? Maybe I can check to add Flutter support if it's not too difficult ^^

**Comment by tejainece** [comment]
It definitely works with Flutter. Will make an example.

**Comment by jaumard** [comment]
That would be awesome !!!!

**Comment by jaumard** [comment]
I dig into the source code and didn't see any sqlite adapter. When you say it works with flutter it's with a local database in the phone ?

**Comment by jaumard** [comment]
FYI: I manage to genera a Bean under a flutter project, but I had to downgrade path to 1.6.0 and build_runner to 0.8.9 in order to fix dependency conflicts with flutter :( 

Are you open to PR for an SQLite adapter compatible flutter ? 

Is there any documentation on how create an adapter or should I dig into existing one ?

**Comment by tejainece** [comment]
> FYI: I manage to genera a Bean under a flutter project, but I had to downgrade path to 1.6.0 and build_runner to 0.8.9 in order to fix dependency conflicts with flutter :(

You can use `dependency_overrides:` in your project and set:

```yaml
dependency_overrides:
  path: ^1.6.0
  build_runner: ^0.8.9
```

Hopefully, Flutter will soon move to latest sdk.

**Comment by tejainece** [comment]
> Are you open to PR for an SQLite adapter compatible flutter ?

> Is there any documentation on how create an adapter or should I dig into existing one ?

PRs are always welcome!

This is a very good reference Adapter implementation:

https://github.com/Jaguar-dart/jaguar_orm/blob/master/postgres/lib/src/adapter.dart

**Comment by jaumard** [comment]
Hum I tried the `dependency_overrides` but didn't manage to make it work :( 

This:
```
name: orm_flutter_test
description: A new Flutter application.

dependencies:
  jaguar_orm: "^2.1.1"
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: "^0.8.9"
  jaguar_orm_gen: "^2.1.1"
#    path: "../jaguar_orm/generator"
  flutter_test:
    sdk: flutter

dependency_overrides:
  path: ^1.6.0
  build_runner: ^0.8.9

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

``` 

Give me : 
```
Because every version of flutter_test from sdk depends on analyzer 0.31.2-alpha.2 and every version of jaguar_orm_gen depends on analyzer ^0.32.0, flutter_test from sdk is incompatible with jaguar_orm_gen.
So, because orm_flutter_test depends on both jaguar_orm_gen ^2.1.1 and flutter_test any from sdk, version solving failed.
pub get failed (1)
```

Thanks for the reference ! I'll take a look and try implement something ^^
